import { Link } from 'react-router-dom';

export default function LandingPage() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[90vh] text-center px-4 space-y-8 animate-in fade-in zoom-in duration-500">
      <h1 className="text-6xl font-extrabold tracking-tight lg:text-7xl bg-gradient-to-r from-primary to-blue-500 bg-clip-text text-transparent pb-2">
        Share Smarter. <br /> Borrow Faster.
      </h1>
      <p className="text-xl text-muted-foreground max-w-[600px] leading-relaxed">
        Algorithmically driven peer-to-peer lending for your campus. Real-time matching based on proximity and trust.
      </p>
      
      <div className="flex gap-4 pt-4">
        <Link 
          to="/auth" 
          className="px-8 py-3 text-lg font-semibold rounded-full bg-primary text-primary-foreground hover:bg-primary/90 transition-all shadow-lg hover:shadow-primary/25"
        >
          Get Started
        </Link>
        <Link 
          to="/about" 
          className="px-8 py-3 text-lg font-semibold rounded-full bg-secondary text-secondary-foreground hover:bg-secondary/80 transition-all"
        >
          Learn More
        </Link>
      </div>

      <div className="pt-16 grid grid-cols-1 md:grid-cols-3 gap-8 text-left max-w-5xl">
        <div className="p-6 rounded-2xl bg-card border shadow-sm">
          <h3 className="text-xl font-bold mb-2">Smart Graph Matching</h3>
          <p className="text-muted-foreground">O(E log V) Dijkstra-powered engine matches you with the absolute best lenders instantly.</p>
        </div>
        <div className="p-6 rounded-2xl bg-card border shadow-sm">
          <h3 className="text-xl font-bold mb-2">Instant WebSocket Alerts</h3>
          <p className="text-muted-foreground">Receive real-time notifications the moment a match is generated by the system.</p>
        </div>
        <div className="p-6 rounded-2xl bg-card border shadow-sm">
          <h3 className="text-xl font-bold mb-2">Dynamic Trust Scores</h3>
          <p className="text-muted-foreground">A robust, DFS-cycle-checked rating system ensuring safe lending environments.</p>
        </div>
      </div>
    </div>
  );
}
